### PR TITLE
feat: add AddToLogEntry function

### PR DESCRIPTION
**Pull request by dlsrb6342**
```golang
if le := accesslog.GetLogEntry(ctx); le != nil {
	le.Add(func(e *zerolog.Event) { e.Str("user_id", user.Id) })
}
```
* "Get LogEntry and Add" is too verbose. 
* I think we can do same thing with `AddToLogEntry` function

### CODE REVIEW

**Comment by zzerjae** [comment]
How about AddFields instead of AddToLogEntry?

**Comment by dlsrb6342** [comment]
First of all, I think `LogEntry.Add()` is not a proper name. We can more things with `zerolog.Event`, ex `e.Send()`. 
we need to prevent to do other things except "Add Fields". Then, `AddFields` would be great.

**Comment by zzerjae** [comment]
That's good point. I think we should consider changing the Event to an interface to limit actions other than adding Fields.

**Comment by dlsrb6342** [comment]
Yes. Close this PR and I'll make an issue for adding interface to limit actions.

**Pull request closed without merging**
